services:
  mysql:
    image: mysql:8.4
    container_name: paymenttracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "paymenttracker",
          "-p${MYSQL_PASSWORD}",
        ]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 5s

volumes:
  mysql_data:
